### PR TITLE
Updated Tokio to 1.x

### PR DESCRIPTION
**Pull request by guillaume-be**
Hello @epwalsh ,

This this implementation is a reference I like to use when people have questions regarding using rust-bert as an API, I thought i'd be nice to keep its dependencies up to date. There has been quite a number of changes with the release of Tokio 1.x, I thought it'd be nice to validate that the code proposed here still works.

Thanks!

### CODE REVIEW

**Review by epwalsh — APPROVED** [review]
Looks great @guillaume-be!

I think the ["Setup" section](https://github.com/epwalsh/rust-dl-webserver#setup) of the README may be out of date too. We don't need to manually run the `utils/download-dependencies_gpt2.py` script anymore, right?

**Comment by epwalsh** [comment]
Can you take a look at https://github.com/epwalsh/rust-dl-webserver/pull/26?

**Comment by guillaume-be** [comment]
Looks good - GPT2 indeed gets automatically downloaded - and the Readme seems up to date. Thanks again for this repository it is very useful as an illustration of serving these models!

**Comment by epwalsh** [comment]
My pleasure!

**Pull request merged**
